version: '3.8'

services:
  # CBI Microservice Application
  cbi-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cbi-microservice
    ports:
      - "8080:8080"  # Main application port
      - "8081:8081"  # Management/actuator port
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-cbi_backend}
      DB_SCHEMA: ${DB_SCHEMA:-public}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password123}

      # Spring profiles
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      # Server configuration
      SERVER_PORT: 8080
      MANAGEMENT_PORT: 8081

      # Cache configuration
      CACHE_TTL: ${CACHE_TTL:-900}
      CACHE_MAX_SIZE: ${CACHE_MAX_SIZE:-100}

      # Refresh configuration
      REFRESH_INTERVAL: ${REFRESH_INTERVAL:-900000}

      # Yaci Store Core configuration
      CARDANO_NODE_HOST: ${CARDANO_NODE_HOST:-localhost}
      CARDANO_NODE_PORT: ${CARDANO_NODE_PORT:-3001}
      CARDANO_PROTOCOL_MAGIC: ${CARDANO_PROTOCOL_MAGIC:-764824073}
      CARDANO_NODE_SOCKET_PATH: ${CARDANO_NODE_SOCKET_PATH:-/opt/cardano/cnode/sockets/node0.socket}
      CARDANO_N2C_PORT: ${CARDANO_N2C_PORT:-3001}
      SYNC_START_SLOT: ${SYNC_START_SLOT:-0}
      
      # Core Store (minimal footprint)
      CORE_STORE_ENABLED: ${CORE_STORE_ENABLED:-true}
      INCLUDE_BLOCK_CBOR: ${INCLUDE_BLOCK_CBOR:-false}
      INCLUDE_TRANSACTION_CBOR: ${INCLUDE_TRANSACTION_CBOR:-false}
      
      # Event Configuration
      EVENTS_ENABLED: ${EVENTS_ENABLED:-true}
      TRANSACTION_EVENTS: ${TRANSACTION_EVENTS:-true}

      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SQL_LOG_LEVEL: ${SQL_LOG_LEVEL:-WARN}

      # JVM options
      JAVA_OPTS: "-Xmx1g -Xms512m -XX:+UseG1GC"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
    networks:
      - cbi-network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: cbi-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-cbi_backend}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cbi-network


volumes:
  postgres_data:
    driver: local

networks:
  cbi-network:
    driver: bridge
